#cloud-config
user: admin
password: admin
chpasswd: { expire: False }
ssh_pwauth: True
users:
  - default
  - name: admin
    groups: sudo
    shell: /bin/bash
    lock_passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL
    passwd: "$6$rounds=4096$utilizaresalt$vQ7.v/x1E/T9XvB8XJ7xM7R5p.E/S1.v8S1.v8S1.v8S1.v8S1.v8S1.v8S1.v8S1.v8S1.v8S1.v8S1."
# Nota: La password arriba es 'admin' hasheada.